--Nombre bd: Sistema de Evidencias

--Carrera

CREATE TABLE CARRERA (
    ID_CARRERA SERIAL,
    NOMBRE_CARRERA VARCHAR(70),
    AREA VARCHAR(70),
    CANTIDAD_MATRICULADOS INT,
    CONSTRAINT PK_CARRERA PRIMARY KEY (ID_CARRERA)
);


--Rol

CREATE TABLE ROL(
	ID_ROL SERIAL,
	NOMBRE_ROL VARCHAR(70),
	CONSTRAINT PK_ROL PRIMARY KEY(ID_ROL)
);

--Unidad

CREATE TABLE UNIDAD(
	ID_UNIDAD SERIAL,
	NOMBRE_UNIDAD VARCHAR(70),
	UNIDAD_DEFECTO BOOLEAN,
	CONSTRAINT PK_UNIDAD PRIMARY KEY(ID_UNIDAD)
);

--Criterios

CREATE TABLE CRITERIOS(
	ID_CRITERIOS SERIAL,
	NOMBRE_CRITERIOS VARCHAR(70),
	CODIGO_CRITERIOS INT,
	DESCRIPCION_CRITERIOS VARCHAR(70),
	ESTADO_CRITERIOS BOOLEAN,
	CONSTRAINT PK_CRITERIOS PRIMARY KEY(ID_CRITERIOS)
);

--Debilidades

CREATE TABLE DEBILIDADES(
	ID_DEBILIDADES SERIAL,
	DESCRIPCION_DEBILIDADES VARCHAR(70),
	ESTADO_DEBILIDADES BOOLEAN,
	ID_CRITERIOS INT,
	CONSTRAINT PK_DEBILIDADES PRIMARY KEY(ID_DEBILIDADES),
	CONSTRAINT FK_DEBILIDADES FOREIGN KEY(ID_CRITERIOS) REFERENCES CRITERIOS(ID_CRITERIOS)
);

--Registro

CREATE TABLE REGISTRO(
	ID_REGISTRO SERIAL,
	DATOS_REGISTRO VARCHAR(70),
	CONTENIDO_REGISTRO VARCHAR(70),
	CONSTRAINT PK_REGISTRO PRIMARY KEY(ID_REGISTRO)
);

--Facultad

CREATE TABLE FACULTAD(
	ID_FACULTAD SERIAL,
	NOMBRE_FACULTAD VARCHAR(70),
	CONSTRAINT PK_FACULTAD PRIMARY KEY(ID_FACULTAD)
);

--Procesos

CREATE TABLE PROCESOS(
	ID_PROCESOS SERIAL,
	CODIGO_PROCESOS INT,
	NOMBRE_PROCESOS VARCHAR(70),
	ESTADO_PROCESOS BOOLEAN,
	CONSTRAINT PK_PROCESOS PRIMARY KEY(ID_PROCESOS)
);

--Detalle DAC

CREATE TABLE DETALLE_DAC(
	ID_DETALLE_DAC SERIAL,
	REVISADO_DAC BOOLEAN,
	ESTADO_DAC BOOLEAN,
	COMENTARIO_DAC VARCHAR(100),
	CONSTRAINT PK_DETALLE_DAC PRIMARY KEY(ID_DETALLE_DAC)
);

--Detalle Comite

CREATE TABLE DETALLE_COMITE(
	ID_DETALLE_COMITE SERIAL,
	REVISADO_COMITE BOOLEAN,
	ESTADO_COMITE BOOLEAN,
	COMENTARIO_COMITE VARCHAR(70),
	CONSTRAINT PK_DETALLE_COMITE PRIMARY KEY(ID_DETALLE_COMITE)
);

--Detalle Revisor 

CREATE TABLE DETALLE_REVISOR(
	ID_DETALLE_REVISOR SERIAL,
	REVISADO_REVISOR BOOLEAN,
	ESTADO_REVISOR BOOLEAN,
	COMENTARIO_REVISOR VARCHAR(100),
	CONSTRAINT PK_DETALLE_REVISOR PRIMARY KEY(ID_DETALLE_REVISOR)
);

--Ambito Academico

CREATE TABLE AMBITO_ACADEMICO(
	ID_AMBITO_ACADEMICO SERIAL,
	NOMBRE_AMBITO_ACADEMICO VARCHAR(70),
	ESTADO_AMBITO_ACADEMICO BOOLEAN,
	CONSTRAINT PK_AMBITO_ACADEMICO PRIMARY KEY(ID_AMBITO_ACADEMICO)
);

--Ambito Geografico

CREATE TABLE AMBITO_GEOGRAFICO(
	ID_AMBITO_GEOGRAFICO SERIAL,
	NOMBRE_AMBITO_GEOGRAFICO VARCHAR(70),
	ESTADO_AMBITO_GEOGRAFICO BOOLEAN,
	CONSTRAINT PK_AMBITO_GEOGRAFICO PRIMARY KEY(ID_AMBITO_GEOGRAFICO)
);

--Usuarios

CREATE TABLE USUARIOS(
	ID_USUARIO SERIAL,
	RUT_USUARIO INT,
	NOMBRE_USUARIO VARCHAR(70),
	APELLIDO1_USUARIO VARCHAR(20),
	APELLIDO2_USUARIO VARCHAR(20),
	CLAVE_USUARIO VARCHAR(70),
	CORREO_USUARIO VARCHAR(70),
	ESTADO_USUARIO BOOLEAN,
	ID_ROL INT,
	ID_UNIDAD INT,
	CONSTRAINT PK_USUARIOS PRIMARY KEY(ID_USUARIO),
	CONSTRAINT FK_USUARIOS_ROL FOREIGN KEY(ID_ROL) REFERENCES ROL(ID_ROL),
	CONSTRAINT FK_USUARIOS_UNIDAD FOREIGN KEY(ID_UNIDAD) REFERENCES UNIDAD(ID_UNIDAD)
);

--Impacto

CREATE TABLE IMPACTO(
	ID_IMPACTO SERIAL,
	INTERNO_EXTERNO VARCHAR(10),
	CONSTRAINT PK_IMPACTO PRIMARY KEY(ID_IMPACTO)
);

--Estado

CREATE TABLE ESTADO(
	ID_ESTADO SERIAL,
	ONLINE_PRESENCIAL VARCHAR(10),
	CONSTRAINT PK_ESTADO PRIMARY KEY(ID_ESTADO)
);

--Evidencias

CREATE TABLE EVIDENCIAS(
	ID_EVIDENCIAS SERIAL,
	NUMERO_FOLIO VARCHAR(70),
	CORREO_USUARIO VARCHAR(70),
	RUT_USUARIO INT,
	FECHA_EVIDENCIA TIMESTAMP WITH TIME ZONE ,
	NUMERO_DE_MEJORAS INT,
	DESCRIPCION VARCHAR(70),
	RESULTADO VARCHAR(70),
	ALMACENAMIENTO VARCHAR(70),
	UNIDADES_PERSONAS_EVIDENCIAS INT,
	PALABRA_CLAVE VARCHAR(20),
	NOMBRE_CORTO_EVIDENCIA VARCHAR(10),
	FECHA_CREACION TIMESTAMP WITH TIME ZONE,
	FECHA_ACTUALIZACION TIMESTAMP WITH TIME ZONE,
	ASISTENTES_INTERNOS_AUTORIDADES INT,
	ASISTENTES_INTERNOS_ADMINISTRATIVOS INT,
	ASISTENTES_INTERNOS_DOCENTES INT,
	ASISTENTES_INTERNOS_ESTUDIANTES INT,
	ASISTENTES_EXTERNOS_AUTORIDADES INT,
	ASISTENTES_EXTERNOS_ADMINISTRATIVOS INT,
	ASISTENTES_EXTERNOS_DOCENTES INT,
	ASISTENTES_EXTERNOS_ESTUDIANTES INT,
	ARCHIVO_ADJUNTO BYTEA,
	ID_DETALLE_REVISOR_EVIDENCIAS INT,
	ID_DETALLE_DAC_EVIDENCIAS INT,
	ID_DETALLE_COMITE_EVIDENCIAS INT,
	ID_USUARIO INT,
	ID_DEBILIDADES INT,
	ID_UNIDAD INT,
	ID_AMBITO_GEOGRAFICO INT,
	ID_AMBITO_ACADEMICO INT,
	ID_REGISTROS INT,
	ID_CARRERA INT,
	ID_FACULTAD INT,
	ID_PROCESOS INT,
	ID_IMPACTO INT,
	ID_ESTADO INT,
	ID_CRITERIOS INT,
	CONSTRAINT PK_EVIDENCIAS PRIMARY KEY(ID_EVIDENCIAS),
	CONSTRAINT FK_EVIDENCIAS_DETALLE_REVISOR FOREIGN KEY(ID_DETALLE_REVISOR_EVIDENCIAS) REFERENCES DETALLE_REVISOR(ID_DETALLE_REVISOR),
	CONSTRAINT FK_EVIDENCIAS_DETALLE_DAC FOREIGN KEY(ID_DETALLE_DAC_EVIDENCIAS) REFERENCES DETALLE_DAC(ID_DETALLE_DAC),
	CONSTRAINT FK_EVIDENCIAS_DETALLE_COMITE FOREIGN KEY(ID_DETALLE_COMITE_EVIDENCIAS) REFERENCES DETALLE_COMITE(ID_DETALLE_COMITE),
	CONSTRAINT FK_EVIDENCIAS_USUARIOS FOREIGN KEY(ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
	CONSTRAINT FK_EVIDENCIAS_DEBILIDADES FOREIGN KEY(ID_DEBILIDADES) REFERENCES DEBILIDADES(ID_DEBILIDADES),
	CONSTRAINT FK_EVIDENCIAS_UNIDAD FOREIGN KEY(ID_UNIDAD) REFERENCES UNIDAD(ID_UNIDAD),
	CONSTRAINT FK_EVIDENCIAS_AMBITO_ACADEMICO FOREIGN KEY(ID_AMBITO_ACADEMICO) REFERENCES AMBITO_ACADEMICO(ID_AMBITO_ACADEMICO),
	CONSTRAINT FK_EVIDENCIAS_AMBITO_GEOGRAFICO FOREIGN KEY(ID_AMBITO_GEOGRAFICO) REFERENCES AMBITO_GEOGRAFICO(ID_AMBITO_GEOGRAFICO),
	CONSTRAINT FK_EVIDENCIAS_REGISTROS FOREIGN KEY(ID_REGISTROS) REFERENCES REGISTRO(ID_REGISTRO),
	CONSTRAINT FK_EVIDENCIAS_CARRERA FOREIGN KEY(ID_CARRERA) REFERENCES CARRERA(ID_CARRERA),
	CONSTRAINT FK_EVIDENCIAS_FACULTAD FOREIGN KEY(ID_FACULTAD) REFERENCES FACULTAD(ID_FACULTAD),
	CONSTRAINT FK_EVIDENCIAS_PROCESOS FOREIGN KEY(ID_PROCESOS) REFERENCES PROCESOS(ID_PROCESOS),
	CONSTRAINT FK_EVIDENCIAS_IMPACTO FOREIGN KEY(ID_IMPACTO) REFERENCES IMPACTO(ID_IMPACTO),
	CONSTRAINT FK_EVIDENCIAS_ESTADO FOREIGN KEY(ID_ESTADO) REFERENCES ESTADO(ID_ESTADO),
	CONSTRAINT FK_EVIDENCIAS_CRITERIOS FOREIGN KEY (ID_CRITERIOS) REFERENCES CRITERIOS(ID_CRITERIOS)
);