import {Router} from 'express';
import {getAmbitoGeografico, newAmbitoGeografico, getAmbitosGeograficos,deleteAmbitoGeografico, updateAmbitoGeografico, buscarAmbGeo} from '../controllers/ambito_geografico';
// import validateToken from './validate-token';
const router = Router();
router.get('/lista',getAmbitosGeograficos);
router.post('/',newAmbitoGeografico);
router.get('/:id',getAmbitoGeografico);
router.delete('/:id',deleteAmbitoGeografico);
router.put('/:id',updateAmbitoGeografico);
router.get('buscar', buscarAmbGeo);
export default router;