import {Router} from 'express';
import {getAmbitoAcademico, newAmbitoAcademico, getAmbitosAcademicos,deleteAmbitoAcademico, updateAmbitoAcademico} from '../controllers/ambito_academico';
// import validateToken from './validate-token';
const router = Router();
router.get('/lista',getAmbitosAcademicos);
router.post('/',newAmbitoAcademico);
router.get('/:id',getAmbitoAcademico);
router.delete('/:id',deleteAmbitoAcademico);
router.put('/:id',updateAmbitoAcademico);
export default router;