import {Router} from 'express';
import {getProceso,getProcesos, newProceso ,deleteProceso, updateProceso} from '../controllers/proceso';
// import validateToken from './validate-token';
const router = Router();
router.get('/lista',getProcesos);
router.post('/',newProceso);
router.get('/:id',getProceso);
router.delete('/:id',deleteProceso);
router.put('/:id',updateProceso);
export default router;