import {Router} from 'express';
import {getUnidad, newUnidad, getOneUnidad,deleteUnidad, updateUnidad, buscarUnidad} from '../controllers/unidad';
import validateToken from './validate-token';
const router = Router();
router.get('/lista',validateToken, getUnidad);
router.post('/',validateToken, newUnidad);
router.get('/:id',validateToken, getOneUnidad);
router.delete('/:id',validateToken, deleteUnidad);
router.put('/:id',validateToken, updateUnidad);
router.get('/buscar',validateToken, buscarUnidad);
export default router;